language: go
sudo: false
go:
  - 1.4.2
before_script:
  - export QBOXROOT=$TRAVIS_BUILD_DIR/..
script:
  - cd $QBOXROOT
  - git clone git@github.com:qbox/base.git
  - cd $QBOXROOT/base; git checkout $TRAVIS_BRANCH
  - cd $TRAVIS_BUILD_DIR; source env.sh
  - make
  - make travis_test
  - make style

