// DON'T EDIT THIS FILE!
// GENERATED BY: go run mkgobbolthandler/*.go > bolt_handler.go
//
package qfusegate

import (
	"encoding/gob"
	"bazil.org/fuse"

	. "golang.org/x/net/context"
	. "qiniu.com/boltfs.proto.v1"
)

func handleInitRequest(ctx Context, host string, req *fuse.InitRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(InitResponse)
	args := &InitRequest{
		Major: req.Major,
		Minor: req.Minor,
		MaxReadahead: req.MaxReadahead,
		Flags: req.Flags,
	}
	err := client.CallWithGob(ctx, ret, "POST", host + "/v1/init", args)
	if err != nil {
		replyError(req, err)
		return
	}

	fuseResp := new(fuse.InitResponse)
	fuseResp.MaxReadahead = ret.MaxReadahead
	fuseResp.Flags = ret.Flags
	fuseResp.MaxWrite = ret.MaxWrite
	req.Respond(fuseResp)
}

func handleDestroyRequest(ctx Context, host string, req *fuse.DestroyRequest) {

	client := newBoltClient(&req.Header, nil)

	err := client.Call(ctx, nil, "POST", host + "/v1/destroy")
	if err != nil {
		replyError(req, err)
		return
	}
	req.Respond()
}

func handleStatfsRequest(ctx Context, host string, req *fuse.StatfsRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(StatfsResponse)
	err := client.Call(ctx, ret, "POST", host + "/v1/statfs")
	if err != nil {
		replyError(req, err)
		return
	}

	fuseResp := new(fuse.StatfsResponse)
	fuseResp.Blocks = ret.Blocks
	fuseResp.Bfree = ret.Bfree
	fuseResp.Bavail = ret.Bavail
	fuseResp.Files = ret.Files
	fuseResp.Ffree = ret.Ffree
	fuseResp.Bsize = ret.Bsize
	fuseResp.Namelen = ret.Namelen
	fuseResp.Frsize = ret.Frsize
	req.Respond(fuseResp)
}

func handleAccessRequest(ctx Context, host string, req *fuse.AccessRequest) {

	client := newBoltClient(&req.Header, nil)

	args := &AccessRequest{
		Inode: uint64(req.Node),
		Mask: req.Mask,
	}
	err := client.CallWithGob(ctx, nil, "POST", host + "/v1/access", args)
	if err != nil {
		replyError(req, err)
		return
	}
	req.Respond()
}

func handleGetattrRequest(ctx Context, host string, req *fuse.GetattrRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(GetattrResponse)
	args := &GetattrRequest{
		Inode: uint64(req.Node),
	}
	err := client.CallWithGob(ctx, ret, "POST", host + "/v1/getattr", args)
	if err != nil {
		replyError(req, err)
		return
	}

	fuseResp := new(fuse.GetattrResponse)
	assignAttr(&fuseResp.Attr, &ret.Attr)
	req.Respond(fuseResp)
}

func handleListxattrRequest(ctx Context, host string, req *fuse.ListxattrRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(ListxattrResponse)
	args := &ListxattrRequest{
		Inode: uint64(req.Node),
		Size: req.Size,
		Position: req.Position,
	}
	err := client.CallWithGob(ctx, ret, "POST", host + "/v1/listxattr", args)
	if err != nil {
		replyError(req, err)
		return
	}

	fuseResp := new(fuse.ListxattrResponse)
	fuseResp.Xattr = ret.XattrNames
	req.Respond(fuseResp)
}

func handleGetxattrRequest(ctx Context, host string, req *fuse.GetxattrRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(GetxattrResponse)
	args := &GetxattrRequest{
		Inode: uint64(req.Node),
		Size: req.Size,
		Position: req.Position,
		Name: req.Name,
	}
	err := client.CallWithGob(ctx, ret, "POST", host + "/v1/getxattr", args)
	if err != nil {
		replyError(req, err)
		return
	}

	fuseResp := new(fuse.GetxattrResponse)
	fuseResp.Xattr = ret.Xattr
	req.Respond(fuseResp)
}

func handleRemovexattrRequest(ctx Context, host string, req *fuse.RemovexattrRequest) {

	client := newBoltClient(&req.Header, nil)

	args := &RemovexattrRequest{
		Inode: uint64(req.Node),
		Name: req.Name,
	}
	err := client.CallWithGob(ctx, nil, "POST", host + "/v1/removexattr", args)
	if err != nil {
		replyError(req, err)
		return
	}
	req.Respond()
}

func handleSetxattrRequest(ctx Context, host string, req *fuse.SetxattrRequest) {

	client := newBoltClient(&req.Header, nil)

	args := &SetxattrRequest{
		Inode: uint64(req.Node),
		Flags: req.Flags,
		Position: req.Position,
		Name: req.Name,
		Xattr: req.Xattr,
	}
	err := client.CallWithGob(ctx, nil, "POST", host + "/v1/setxattr", args)
	if err != nil {
		replyError(req, err)
		return
	}
	req.Respond()
}

func handleLookupRequest(ctx Context, host string, req *fuse.LookupRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(LookupResponse)
	args := &LookupRequest{
		Inode: uint64(req.Node),
		Name: req.Name,
	}
	err := client.CallWithGob(ctx, ret, "POST", host + "/v1/lookup", args)
	if err != nil {
		replyError(req, err)
		return
	}

	fuseResp := new(fuse.LookupResponse)
	fuseResp.Node = fuse.NodeID(ret.Inode)
	fuseResp.Generation = ret.Generation
	fuseResp.EntryValid = ret.EntryValid
	assignAttr(&fuseResp.Attr, &ret.Attr)
	req.Respond(fuseResp)
}

func handleOpenRequest(ctx Context, host string, req *fuse.OpenRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(OpenResponse)
	args := &OpenRequest{
		Inode: uint64(req.Node),
		Flags: req.Flags,
		Dir: req.Dir,
	}
	err := client.CallWithGob(ctx, ret, "POST", host + "/v1/open", args)
	if err != nil {
		replyError(req, err)
		return
	}

	fuseResp := new(fuse.OpenResponse)
	fuseResp.Handle = fuse.HandleID(ret.Handle)
	fuseResp.Flags = ret.Flags
	req.Respond(fuseResp)
}

func handleCreateRequest(ctx Context, host string, req *fuse.CreateRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(CreateResponse)
	args := &CreateRequest{
		Inode: uint64(req.Node),
		Flags: req.Flags,
		Mode: req.Mode,
		Name: req.Name,
	}
	err := client.CallWithGob(ctx, ret, "POST", host + "/v1/create", args)
	if err != nil {
		replyError(req, err)
		return
	}

	fuseResp := new(fuse.CreateResponse)
	fuseResp.Node = fuse.NodeID(ret.Inode)
	fuseResp.Generation = ret.Generation
	fuseResp.EntryValid = ret.EntryValid
	assignAttr(&fuseResp.Attr, &ret.Attr)
	fuseResp.Handle = fuse.HandleID(ret.Handle)
	fuseResp.Flags = ret.Flags
	req.Respond(fuseResp)
}

func handleMkdirRequest(ctx Context, host string, req *fuse.MkdirRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(MkdirResponse)
	args := &MkdirRequest{
		Inode: uint64(req.Node),
		Mode: req.Mode,
		Name: req.Name,
	}
	err := client.CallWithGob(ctx, ret, "POST", host + "/v1/mkdir", args)
	if err != nil {
		replyError(req, err)
		return
	}

	fuseResp := new(fuse.MkdirResponse)
	fuseResp.Node = fuse.NodeID(ret.Inode)
	fuseResp.Generation = ret.Generation
	fuseResp.EntryValid = ret.EntryValid
	assignAttr(&fuseResp.Attr, &ret.Attr)
	req.Respond(fuseResp)
}

func handleSymlinkRequest(ctx Context, host string, req *fuse.SymlinkRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(SymlinkResponse)
	args := &SymlinkRequest{
		Inode: uint64(req.Node),
		NewName: req.NewName,
		Target: req.Target,
	}
	err := client.CallWithGob(ctx, ret, "POST", host + "/v1/symlink", args)
	if err != nil {
		replyError(req, err)
		return
	}

	fuseResp := new(fuse.SymlinkResponse)
	fuseResp.Node = fuse.NodeID(ret.Inode)
	fuseResp.Generation = ret.Generation
	fuseResp.EntryValid = ret.EntryValid
	assignAttr(&fuseResp.Attr, &ret.Attr)
	req.Respond(fuseResp)
}

func handleReadlinkRequest(ctx Context, host string, req *fuse.ReadlinkRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(ReadlinkResponse)
	args := &ReadlinkRequest{
		Inode: uint64(req.Node),
	}
	err := client.CallWithGob(ctx, ret, "POST", host + "/v1/readlink", args)
	if err != nil {
		replyError(req, err)
		return
	}
	req.Respond(ret.Target)
}

func handleLinkRequest(ctx Context, host string, req *fuse.LinkRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(LinkResponse)
	args := &LinkRequest{
		Inode: uint64(req.Node),
		OldInode: uint64(req.OldNode),
		NewName: req.NewName,
	}
	err := client.CallWithGob(ctx, ret, "POST", host + "/v1/link", args)
	if err != nil {
		replyError(req, err)
		return
	}

	fuseResp := new(fuse.LookupResponse)
	fuseResp.Node = fuse.NodeID(ret.Inode)
	fuseResp.Generation = ret.Generation
	fuseResp.EntryValid = ret.EntryValid
	assignAttr(&fuseResp.Attr, &ret.Attr)
	req.Respond(fuseResp)
}

func handleMknodRequest(ctx Context, host string, req *fuse.MknodRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(MknodResponse)
	args := &MknodRequest{
		Inode: uint64(req.Node),
		Mode: req.Mode,
		Rdev: req.Rdev,
		Name: req.Name,
	}
	err := client.CallWithGob(ctx, ret, "POST", host + "/v1/mknod", args)
	if err != nil {
		replyError(req, err)
		return
	}

	fuseResp := new(fuse.LookupResponse)
	fuseResp.Node = fuse.NodeID(ret.Inode)
	fuseResp.Generation = ret.Generation
	fuseResp.EntryValid = ret.EntryValid
	assignAttr(&fuseResp.Attr, &ret.Attr)
	req.Respond(fuseResp)
}

func handleRenameRequest(ctx Context, host string, req *fuse.RenameRequest) {

	client := newBoltClient(&req.Header, nil)

	args := &RenameRequest{
		NewDirInode: uint64(req.NewDir),
		OldName: req.OldName,
		NewName: req.NewName,
	}
	err := client.CallWithGob(ctx, nil, "POST", host + "/v1/rename", args)
	if err != nil {
		replyError(req, err)
		return
	}
	req.Respond()
}

func handleRemoveRequest(ctx Context, host string, req *fuse.RemoveRequest) {

	client := newBoltClient(&req.Header, nil)

	args := &RemoveRequest{
		Inode: uint64(req.Node),
		Dir: req.Dir,
		Name: req.Name,
	}
	err := client.CallWithGob(ctx, nil, "POST", host + "/v1/remove", args)
	if err != nil {
		replyError(req, err)
		return
	}
	req.Respond()
}

func handleReadRequest(ctx Context, host string, req *fuse.ReadRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(ReadResponse)
	args := &ReadRequest{
		Handle: uint64(req.Handle),
		Offset: req.Offset,
		Size: req.Size,
		Dir: req.Dir,
	}
	err := client.CallWithGob(ctx, ret, "POST", host + "/v1/read", args)
	if err != nil {
		replyError(req, err)
		return
	}

	fuseResp := new(fuse.ReadResponse)
	fuseResp.Data = ret.Data
	req.Respond(fuseResp)
}

func handleWriteRequest(ctx Context, host string, req *fuse.WriteRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(WriteResponse)
	args := &WriteRequest{
		Handle: uint64(req.Handle),
		Offset: req.Offset,
		Flags: req.Flags,
		Data: req.Data,
	}
	err := client.CallWithGob(ctx, ret, "POST", host + "/v1/write", args)
	if err != nil {
		replyError(req, err)
		return
	}

	fuseResp := new(fuse.WriteResponse)
	fuseResp.Size = ret.Size
	req.Respond(fuseResp)
}

func handleSetattrRequest(ctx Context, host string, req *fuse.SetattrRequest) {

	client := newBoltClient(&req.Header, nil)

	ret := new(SetattrResponse)
	args := &SetattrRequest{
		Valid: req.Valid,
		Handle: uint64(req.Handle),
		Size: req.Size,
		Atime: Time(req.Atime.UnixNano()),
		Mtime: Time(req.Mtime.UnixNano()),
		Mode: req.Mode,
		Uid: req.Uid,
		Gid: req.Gid,
		Bkuptime: Time(req.Bkuptime.UnixNano()),
		Chgtime: Time(req.Chgtime.UnixNano()),
		Crtime: Time(req.Crtime.UnixNano()),
		Flags: req.Flags,
	}
	err := client.CallWithGob(ctx, ret, "POST", host + "/v1/setattr", args)
	if err != nil {
		replyError(req, err)
		return
	}

	fuseResp := new(fuse.SetattrResponse)
	assignAttr(&fuseResp.Attr, &ret.Attr)
	req.Respond(fuseResp)
}

func handleFlushRequest(ctx Context, host string, req *fuse.FlushRequest) {

	client := newBoltClient(&req.Header, nil)

	args := &FlushRequest{
		Handle: uint64(req.Handle),
		LockOwner: req.LockOwner,
		Flags: req.Flags,
	}
	err := client.CallWithGob(ctx, nil, "POST", host + "/v1/flush", args)
	if err != nil {
		replyError(req, err)
		return
	}
	req.Respond()
}

func handleFsyncRequest(ctx Context, host string, req *fuse.FsyncRequest) {

	client := newBoltClient(&req.Header, nil)

	args := &FsyncRequest{
		Handle: uint64(req.Handle),
		Flags: req.Flags,
		Dir: req.Dir,
	}
	err := client.CallWithGob(ctx, nil, "POST", host + "/v1/fsync", args)
	if err != nil {
		replyError(req, err)
		return
	}
	req.Respond()
}

func handleReleaseRequest(ctx Context, host string, req *fuse.ReleaseRequest) {

	client := newBoltClient(&req.Header, nil)

	args := &ReleaseRequest{
		Handle: uint64(req.Handle),
		Flags: req.Flags,
		ReleaseFlags: req.ReleaseFlags,
		LockOwner: req.LockOwner,
		Dir: req.Dir,
	}
	err := client.CallWithGob(ctx, nil, "POST", host + "/v1/release", args)
	if err != nil {
		replyError(req, err)
		return
	}
	req.Respond()
}

func handleForgetRequest(ctx Context, host string, req *fuse.ForgetRequest) {

	client := newBoltClient(&req.Header, nil)

	args := &ForgetRequest{
		Inode: uint64(req.Node),
		LookupReqid: uint64(req.N),
	}
	err := client.CallWithGob(ctx, nil, "POST", host + "/v1/forget", args)
	if err != nil {
		replyError(req, err)
		return
	}
	req.Respond()
}

func handleInterruptRequest(ctx Context, host string, req *fuse.InterruptRequest) {

	client := newBoltClient(&req.Header, nil)

	args := &InterruptRequest{
		IntrReqId: uint64(req.IntrID),
	}
	err := client.CallWithGob(ctx, nil, "POST", host + "/v1/interrupt", args)
	if err != nil {
		replyError(req, err)
		return
	}
	req.Respond()
}

func init() {

	gob.RegisterName("InitResponse", InitResponse{})
	gob.RegisterName("InitRequest", InitRequest{})
	gob.RegisterName("StatfsResponse", StatfsResponse{})
	gob.RegisterName("AccessRequest", AccessRequest{})
	gob.RegisterName("GetattrResponse", GetattrResponse{})
	gob.RegisterName("GetattrRequest", GetattrRequest{})
	gob.RegisterName("ListxattrResponse", ListxattrResponse{})
	gob.RegisterName("ListxattrRequest", ListxattrRequest{})
	gob.RegisterName("GetxattrResponse", GetxattrResponse{})
	gob.RegisterName("GetxattrRequest", GetxattrRequest{})
	gob.RegisterName("RemovexattrRequest", RemovexattrRequest{})
	gob.RegisterName("SetxattrRequest", SetxattrRequest{})
	gob.RegisterName("LookupResponse", LookupResponse{})
	gob.RegisterName("LookupRequest", LookupRequest{})
	gob.RegisterName("OpenResponse", OpenResponse{})
	gob.RegisterName("OpenRequest", OpenRequest{})
	gob.RegisterName("CreateResponse", CreateResponse{})
	gob.RegisterName("CreateRequest", CreateRequest{})
	gob.RegisterName("MkdirResponse", MkdirResponse{})
	gob.RegisterName("MkdirRequest", MkdirRequest{})
	gob.RegisterName("SymlinkResponse", SymlinkResponse{})
	gob.RegisterName("SymlinkRequest", SymlinkRequest{})
	gob.RegisterName("ReadlinkResponse", ReadlinkResponse{})
	gob.RegisterName("ReadlinkRequest", ReadlinkRequest{})
	gob.RegisterName("LinkResponse", LinkResponse{})
	gob.RegisterName("LinkRequest", LinkRequest{})
	gob.RegisterName("MknodResponse", MknodResponse{})
	gob.RegisterName("MknodRequest", MknodRequest{})
	gob.RegisterName("RenameRequest", RenameRequest{})
	gob.RegisterName("RemoveRequest", RemoveRequest{})
	gob.RegisterName("ReadResponse", ReadResponse{})
	gob.RegisterName("ReadRequest", ReadRequest{})
	gob.RegisterName("WriteResponse", WriteResponse{})
	gob.RegisterName("WriteRequest", WriteRequest{})
	gob.RegisterName("SetattrResponse", SetattrResponse{})
	gob.RegisterName("SetattrRequest", SetattrRequest{})
	gob.RegisterName("FlushRequest", FlushRequest{})
	gob.RegisterName("FsyncRequest", FsyncRequest{})
	gob.RegisterName("ReleaseRequest", ReleaseRequest{})
	gob.RegisterName("ForgetRequest", ForgetRequest{})
	gob.RegisterName("InterruptRequest", InterruptRequest{})
}

